[package]
name = "sap_macros"
version = "0.1.0-alpha.1"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.39"
syn = { version = "2.0.99", default-features = false, features = [
    "derive",
    "parsing",
    "proc-macro",
] }
